apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockscout
  namespace: crossbell
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: blockscout
      tier: api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: blockscout
        tier: api
      annotations:
        prometheus.io/port: "4000"
        prometheus.io/scrape: "true"
    spec:
      initContainers:
        - image: flosspicks/blockscout
          imagePullPolicy: Always
          name: blockscout-init
          command:
            - bin/blockscout
            - eval
            - '"Elixir.Explorer.ReleaseTasks.create_and_migrate()"'
          envFrom:
            - secretRef:
                name: blockscout
      containers:
        - image: flosspicks/blockscout
          imagePullPolicy: Always
          name: blockscout
          command:
            - bin/blockscout
            - start
          envFrom:
            - secretRef:
                name: blockscout
          ports:
            - containerPort: 4000
              protocol: TCP
          resources:
            requests:
              memory: "2500Mi"
              cpu: "1500m"
            limits:
              memory: "6000Mi"
              cpu: "4000m"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          readinessProbe:
            tcpSocket:
              port: 4000
            initialDelaySeconds: 20
            periodSeconds: 20
          livenessProbe:
            tcpSocket:
              port: 4000
            initialDelaySeconds: 20
            periodSeconds: 20
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
