apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockscout
  namespace: crossbell
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: blockscout
      tier: api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: blockscout
        tier: api
    spec:
      containers:
        - image: ${IMAGE_TAG_RELEASE}
          imagePullPolicy: Always
          name: blockscout
          command:
            - bash
            - -c
            - '"bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"'
          envFrom:
            - secretRef:
                name: blockscout-secret
          ports:
            - containerPort: 4000
              protocol: TCP
          resources:
            requests:
              memory: "2500Mi"
              cpu: "1500m"
            limits:
              memory: "6000Mi"
              cpu: "4000m"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          readinessProbe:
            tcpSocket:
              port: 4000
            initialDelaySeconds: 20
            periodSeconds: 20
          livenessProbe:
            tcpSocket:
              port: 4000
            initialDelaySeconds: 20
            periodSeconds: 20
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
