apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: blockscout
  namespace: crossbell
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`scan.crossbell.io`)
      services:
        - name: blockscout
          port: 4000
