apiVersion: v1
kind: Secret
metadata:
  name: blockscout-secret
  namespace: crossbell
stringData:
  SECRET_KEY_BASE: $SECRET_KEY_BASE
  COIN: CSB
  COIN_NAME: CSB
  ETHEREUM_JSONRPC_VARIANT: geth
  ETHEREUM_JSONRPC_HTTP_URL: http://crossbell-rpc-internal-debug.crossbell/
  DATABASE_URL: $DATABASE_URL
  BLOCK_TRANSFORMER: clique
  SUBNETWORK: Crossbell
  NETWORK: ""
  INDEXER_MEMORY_LIMIT: "4"
  INDEXER_DISABLE_CATALOGED_TOKEN_UPDATER_FETCHER: "true"
  BLOCKSCOUT_HOST: "scan.crossbell.io"
  ETHEREUM_JSONRPC_DEBUG_TRACE_TRANSACTION_TIMEOUT: "30s"
  PORT: "4000"
  LOGO: "/images/blockscout_logo.svg"
type: Opaque
