name: Build and Deploy
on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  build:
    uses: NaturalSelectionLabs/Daedalus/.github/workflows/docker-tpl.yaml@main
    with:
      images: flosspicks/blockscout
      context: .
      dockerfile: ./docker/Dockerfile
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  deploy-prod:
    uses: NaturalSelectionLabs/Daedalus/.github/workflows/deploy-v3-tpl.yaml@main
    needs:
      - build
    with:
      images: flosspicks/blockscout
      tag: sha-${{ github.sha }}
      cluster: prod
      namespace: crossbell
      releaseName: blockscout
      revision: master
      dir: deploy/prod
    secrets:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
